/** 默认绘制国旗，供非法输入回退共用。 */
export const DEFAULT_FLAG = "🇨🇳";

/** 已有专门手写模板的国旗 emoji，避免绘制分支散落字面量。 */
export const TEMPLATE_FLAGS = {
    ad: "🇦🇩",
    ae: "🇦🇪",
    af: "🇦🇫",
    ag: "🇦🇬",
    ai: "🇦🇮",
    al: "🇦🇱",
    am: "🇦🇲",
    ao: "🇦🇴",
    aq: "🇦🇶",
    ar: "🇦🇷",
    as: "🇦🇸",
    at: "🇦🇹",
    australia: "🇦🇺",
    aw: "🇦🇼",
    ax: "🇦🇽",
    az: "🇦🇿",
    ba: "🇧🇦",
    bb: "🇧🇧",
    bd: "🇧🇩",
    be: "🇧🇪",
    bf: "🇧🇫",
    bg: "🇧🇬",
    bh: "🇧🇭",
    bi: "🇧🇮",
    bj: "🇧🇯",
    bl: "🇧🇱",
    bm: "🇧🇲",
    bn: "🇧🇳",
    bo: "🇧🇴",
    bq: "🇧🇶",
    br: "🇧🇷",
    bs: "🇧🇸",
    bt: "🇧🇹",
    bv: "🇧🇻",
    bw: "🇧🇼",
    by: "🇧🇾",
    bz: "🇧🇿",
    ca: "🇨🇦",
    cc: "🇨🇨",
    cd: "🇨🇩",
    cf: "🇨🇫",
    cg: "🇨🇬",
    ch: "🇨🇭",
    ci: "🇨🇮",
    ck: "🇨🇰",
    cl: "🇨🇱",
    cm: "🇨🇲",
    china: "🇨🇳",
    co: "🇨🇴",
    cr: "🇨🇷",
    cu: "🇨🇺",
    cv: "🇨🇻",
    cw: "🇨🇼",
    cx: "🇨🇽",
    cy: "🇨🇾",
    cz: "🇨🇿",
    de: "🇩🇪",
    dj: "🇩🇯",
    dk: "🇩🇰",
    dm: "🇩🇲",
    do: "🇩🇴",
    dz: "🇩🇿",
    ec: "🇪🇨",
    ee: "🇪🇪",
    eg: "🇪🇬",
    eh: "🇪🇭",
    er: "🇪🇷",
    spain: "🇪🇸",
    et: "🇪🇹",
    fi: "🇫🇮",
    fj: "🇫🇯",
    fk: "🇫🇰",
    fm: "🇫🇲",
    fo: "🇫🇴",
    france: "🇫🇷",
    ga: "🇬🇦",
    gb: "🇬🇧",
    gd: "🇬🇩",
    ge: "🇬🇪",
    gf: "🇬🇫",
    gg: "🇬🇬",
    gh: "🇬🇭",
    gi: "🇬🇮",
    gl: "🇬🇱",
    gm: "🇬🇲",
    gn: "🇬🇳",
    gp: "🇬🇵",
    gq: "🇬🇶",
    gr: "🇬🇷",
    gs: "🇬🇸",
    gt: "🇬🇹",
    gu: "🇬🇺",
    gw: "🇬🇼",
    gy: "🇬🇾",
    hk: "🇭🇰",
    hm: "🇭🇲",
    hn: "🇭🇳",
    hr: "🇭🇷",
    ht: "🇭🇹",
    hu: "🇭🇺",
    id: "🇮🇩",
    ie: "🇮🇪",
    il: "🇮🇱",
    im: "🇮🇲",
    in: "🇮🇳",
    io: "🇮🇴",
    iq: "🇮🇶",
    ir: "🇮🇷",
    is: "🇮🇸",
    italy: "🇮🇹",
    je: "🇯🇪",
    jm: "🇯🇲",
    jo: "🇯🇴",
    japan: "🇯🇵",
    ke: "🇰🇪",
    kg: "🇰🇬",
    kh: "🇰🇭",
    ki: "🇰🇮",
    km: "🇰🇲",
    kn: "🇰🇳",
    kp: "🇰🇵",
    kr: "🇰🇷",
    kw: "🇰🇼",
    ky: "🇰🇾",
    kz: "🇰🇿",
    la: "🇱🇦",
    lb: "🇱🇧",
    lc: "🇱🇨",
    li: "🇱🇮",
    lk: "🇱🇰",
    lr: "🇱🇷",
    ls: "🇱🇸",
    lt: "🇱🇹",
    lu: "🇱🇺",
    lv: "🇱🇻",
    ly: "🇱🇾",
    ma: "🇲🇦",
    mc: "🇲🇨",
    md: "🇲🇩",
    me: "🇲🇪",
    mf: "🇲🇫",
    mg: "🇲🇬",
    mh: "🇲🇭",
    mk: "🇲🇰",
    ml: "🇲🇱",
    mm: "🇲🇲",
    mn: "🇲🇳",
    mo: "🇲🇴",
    mp: "🇲🇵",
    mq: "🇲🇶",
    mr: "🇲🇷",
    ms: "🇲🇸",
    mt: "🇲🇹",
    mu: "🇲🇺",
    mv: "🇲🇻",
    mw: "🇲🇼",
    mx: "🇲🇽",
    my: "🇲🇾",
    mz: "🇲🇿",
    na: "🇳🇦",
    nc: "🇳🇨",
    ne: "🇳🇪",
    nf: "🇳🇫",
    ng: "🇳🇬",
    ni: "🇳🇮",
    nl: "🇳🇱",
    no: "🇳🇴",
    np: "🇳🇵",
    nr: "🇳🇷",
    nu: "🇳🇺",
    nz: "🇳🇿",
    om: "🇴🇲",
    pa: "🇵🇦",
    pe: "🇵🇪",
    pf: "🇵🇫",
    pg: "🇵🇬",
    ph: "🇵🇭",
    pk: "🇵🇰",
    pl: "🇵🇱",
    pm: "🇵🇲",
    pn: "🇵🇳",
    pr: "🇵🇷",
    ps: "🇵🇸",
    pt: "🇵🇹",
    pw: "🇵🇼",
    py: "🇵🇾",
    qa: "🇶🇦",
    re: "🇷🇪",
    ro: "🇷🇴",
    rs: "🇷🇸",
    ru: "🇷🇺",
    rw: "🇷🇼",
    sa: "🇸🇦",
    sb: "🇸🇧",
    sc: "🇸🇨",
    sd: "🇸🇩",
    se: "🇸🇪",
    sg: "🇸🇬",
    sh: "🇸🇭",
    si: "🇸🇮",
    sj: "🇸🇯",
    sk: "🇸🇰",
    sl: "🇸🇱",
    sm: "🇸🇲",
    sn: "🇸🇳",
    so: "🇸🇴",
    sr: "🇸🇷",
    ss: "🇸🇸",
    st: "🇸🇹",
    sv: "🇸🇻",
    sx: "🇸🇽",
    sy: "🇸🇾",
    sz: "🇸🇿",
    tc: "🇹🇨",
    td: "🇹🇩",
    tf: "🇹🇫",
    tg: "🇹🇬",
    thailand: "🇹🇭",
    tj: "🇹🇯",
    tk: "🇹🇰",
    tl: "🇹🇱",
    tm: "🇹🇲",
    tn: "🇹🇳",
    to: "🇹🇴",
    tr: "🇹🇷",
    tt: "🇹🇹",
    tv: "🇹🇻",
    tw: "",
    tz: "🇹🇿",
    ua: "🇺🇦",
    ug: "🇺🇬",
    um: "🇺🇲",
    un: "🇺🇳",
    unitedStates: "🇺🇸",
    uy: "🇺🇾",
    uz: "🇺🇿",
    vatican: "🇻🇦",
    vc: "🇻🇨",
    ve: "🇻🇪",
    vg: "🇻🇬",
    vi: "🇻🇮",
    vn: "🇻🇳",
    vu: "🇻🇺",
    wf: "🇼🇫",
    ws: "🇼🇸",
    xk: "🇽🇰",
    ye: "🇾🇪",
    yt: "🇾🇹",
    za: "🇿🇦",
    zm: "🇿🇲",
    zw: "🇿🇼",
} as const;

/** Unicode 区域指示符起始码点，两个区域指示符组成国旗 emoji。 */
export const REGION_INDICATOR_MIN_CODE_POINT = 0x1f1e6;

/** Unicode 区域指示符结束码点，用于限制国旗 emoji 的合法范围。 */
export const REGION_INDICATOR_MAX_CODE_POINT = 0x1f1ff;

/** 离屏 emoji 栅格化时使用的像素倍率，保证高分屏采样足够细。 */
export const DEVICE_PIXEL_RATIO =
    typeof globalThis !== "undefined" &&
    "devicePixelRatio" in globalThis &&
    typeof globalThis.devicePixelRatio === "number"
        ? globalThis.devicePixelRatio
        : 1;

/** 绘制主题：浅色纸张或深色纸张，与 QA 页 data-theme 对应。 */
export type DrawTheme = "light" | "dark";

/** 单套绘制色板：纸张、边框与投影。 */
export interface PaletteColors {
    paper: string;
    frame: string;
    shadow: string;
}

/** 浅色 / 深色色板，与 index.html CSS 变量保持一致。 */
export const PALETTES: Record<DrawTheme, PaletteColors> = {
    light: {
        paper: "#fbfdfa",
        frame: "#d9e3db",
        shadow: "rgba(36, 49, 44, 0.08)",
    },
    dark: {
        paper: "#1a221e",
        frame: "#2d3a34",
        shadow: "rgba(0, 0, 0, 0.28)",
    },
};

/** 默认浅色色板，兼容直接引用 PALETTE 的调用方。 */
export const PALETTE = PALETTES.light;

let activeDrawTheme: DrawTheme = "light";

/** 返回当前绘制主题下的色板。 */
export function getPalette(): PaletteColors {
    return PALETTES[activeDrawTheme];
}

/** 切换绘制主题，切换后需对已有 canvas 重新调用 draw。 */
export function setDrawTheme(theme: DrawTheme): void {
    activeDrawTheme = theme;
}

/** 读取当前绘制主题。 */
export function getDrawTheme(): DrawTheme {
    return activeDrawTheme;
}
